export const SEARCHFIELD_INPUT='SEARCHFIELD_INPUT';
export const FETCHING_ROBOTS_START='FETCHING_ROBOTS_START';
export const FETCHING_ROBOTS_SUCCESS='FETCHING_ROBOTS_SUCCESS';
export const FETCHING_ROBOTS_REJECT='FETCHING_ROBOTS_REJECT';